# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]

name: R-CMD-check

jobs:
  check-logthis:
    runs-on: self-hosted

    name: logthis self-hosted (devcontainer)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Build devcontainer
        run: docker build -f .devcontainer/Dockerfile -t logthis-dev .

      - name: Run R CMD check in devcontainer
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace logthis-dev bash -c "
            cd logthis
            R CMD build .
            R CMD check --as-cran *.tar.gz
          "

  check-logshiny:
    runs-on: self-hosted
    needs: check-logthis

    name: logshiny self-hosted (devcontainer)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Build devcontainer
        run: docker build -f .devcontainer/Dockerfile -t logthis-dev .

      - name: Run R CMD check for logshiny in devcontainer
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace logthis-dev bash -c "
            R CMD INSTALL logthis
            cd logshiny
            R CMD build .
            R CMD check --as-cran *.tar.gz
          "