# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]

name: R-CMD-check

jobs:
  check-logthis:
    runs-on: ${{ matrix.config.os }}

    name: logthis ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: logthis

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          working-directory: logthis

  check-logshiny:
    runs-on: ubuntu-latest
    needs: check-logthis

    name: logshiny ubuntu-latest (release)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      # Install logthis first (dependency)
      - name: Install logthis
        run: |
          R CMD INSTALL logthis
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: logshiny

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          working-directory: logshiny